### ISSUE TITLE
Meal Checkboxes

### ISSUE THREAD

**Issue by mftruso** [mftruso/MealPlanner#1]
Add two checkboxes to a meal: 
- Grocery List Create
- Groceries Purchased

**Comment by mattk410** [comment]
What are you envisioning these boxes doing?

**Comment by mftruso** [comment]
Clicking on a dish in the `/meal/list` view opens the `viewMealModal`. Let's put the checkboxes there and have them ajax update when changed. A new endpoint on the `MealController` will need to be created.
