### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by mftruso** [mftruso/MealPlanner#3]
Replace `<select>`s with typeahead searching https://twitter.github.io/typeahead.js/

**Comment by lavish205** [comment]
can you please provide more details regarding this issue?

**Comment by mftruso** [comment]
@lavish205 thanks for your question! This is a UX enhancement. As the list of Dishes continues to grow, it can be difficult to scroll through a long `<select>` list. Instead, the user should be able to start typing the name of a dish, such as `las` and the suggested `lasagna` should appear below the text field. 

Twitter Typeahead is one such implementation of this pattern, but any will do. 

`dish/list/` has a search field that already behaves similarly to this. 

One place to add this behavior is on `/meal/list` when you click an empty day to add a meal.
![image](https://cloud.githubusercontent.com/assets/5644190/19016428/cc3b663e-87de-11e6-9ee9-5be310efc74c.png)

**Comment by kylec32** [comment]
If this is still available I can give it a stab.

**Comment by kylec32** [comment]
#8 Submitted a pull request to fix this.
